<?php
// Local-only deploy credentials (ignored by Git)
return [
    'host' => 'ftpupload.net',
    'port' => 21,
    'user' => 'if0_40373879',
    'pass' => 'Baddyman734',
    'secure' => true, // FTPS Explicit TLS
    'remoteDir' => '/htdocs/',
    'localRoot' => dirname(__DIR__),
    'include' => ['**/*'],
    'exclude' => [
        '**/.git/**',
        '**/.github/**',
        '**/.vscode/**',
        '**/*.md',
        '**/node_modules/**',
        '**/tasks/**',
        '**/laravel-core/**',
        '**/reset_database.sh',
        '**/database_*.sql',
        'includes/env.php',
        'includes/env.*.php',
        'assets/uploads/**',
        'assets/signatures/**',
    ],
    'extra' => [
        'assets/uploads/.htaccess',
        'assets/signatures/.htaccess',
        'login.php',
        'register.php',
        'logout.php',
        'index.php',
        'select-module.php',
        'messages.php',
        'notifications.php',
        'assets/js/voucher-v5.v10.js',
        'assets/js/voucher-v5.js',
        'assets/js/chatbot.js',
        'assets/js/chatbot-bootstrap.js',
        'assets/css/chatbot.css',
        'chatbot_api.php',
        'includes/chatbot_guides.php',
    ],
];
