<?php require_once '../../includes/functions.php';  ?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>New Account - ERP</title><link rel="stylesheet" href="../../assets/css/style.css?v=<?= time() ?>"><style>* { margin: 0; padding: 0; box-sizing: border-box; } body { margin: 0; padding: 0; background: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; } .header { margin: 0; background: #fff; border-bottom: 1px solid #e0e0e0; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; } .header h1 { font-size: 1.5rem; font-weight: 500; } .container { max-width: 100%; padding: 24px; } .page-wrapper { margin-left: 220px; min-height: 100vh; } @media (max-width: 768px) { .page-wrapper { margin-left: 0; } } .card { background: white; border-radius: 8px; border: 1px solid #e0e0e0; overflow: hidden; } .card-body { padding: 24px; } .form-group { margin-bottom: 16px; } label { display: block; margin-bottom: 8px; font-weight: 500; color: #202124; font-size: 0.875rem; } input, select, textarea { width: 100%; padding: 10px 12px; border: 1px solid #dadce0; border-radius: 4px; font-size: 0.875rem; } .btn { padding: 10px 24px; border-radius: 4px; text-decoration: none; font-size: 0.875rem; font-weight: 500; cursor: pointer; border: none; } .btn-primary { background: #1a73e8; color: white; } .btn-secondary { background: #fff; color: #202124; border: 1px solid #dadce0; } .alert { padding: 12px 16px; border-radius: 4px; margin-bottom: 20px; display: none; } .alert-success { background: #e6f4ea; color: #137333; } .alert-error { background: #fce8e6; color: #c5221f; } /* Keep simple: remove blue hover effects */ .btn:hover { background: inherit; color: inherit; border-color: inherit; } a { color: inherit; text-decoration: none; } a:hover { color: inherit; text-decoration: none; }</style></head>
<body>
<?php include '../includes/sidebar.php'; ?>
<div class="page-wrapper">
<div style="padding: 16px 24px 0; text-align: right;"><a href="chart-of-accounts.php" class="btn btn-secondary">Cancel</a></div><div class="container"><div class="card"><div class="card-body"><div id="alertMessage" class="alert"></div><form id="createAccountForm"><div class="form-group"><label>Account Code *</label><input type="text" name="code" required placeholder="e.g. 1000"></div><div class="form-group"><label>Account Name *</label><input type="text" name="name" required placeholder="e.g. Cash"></div><div class="form-group"><label>Account Type * <a href="account-types.php" class="btn btn-secondary" style="float:right;">Manage Types</a></label><select name="type" id="accountTypeSelect" required><option value="">Loading types...</option></select></div><div class="form-group"><label>Description</label><textarea name="description" rows="3"></textarea></div><div style="margin-top: 24px; text-align: right;"><button type="submit" class="btn btn-primary">Save Account</button></div></form></div></div></div><script>async function loadAccountTypes(){ try { const resp = await fetch('account-types.php'); const html = await resp.text(); const m = html.match(/<tbody>([\s\S]*?)<\\/tbody>/); const select = document.getElementById('accountTypeSelect'); select.innerHTML = '<option value="">Select Type</option>'; if (m){ const rows = Array.from(m[1].matchAll(/<td>([^<]+)<\\/td>/g)).map(x => x[1]); const names = []; for(let i=0;i<rows.length;i+=2){ names.push(rows[i]); } names.forEach(n => { const opt = document.createElement('option'); opt.value = n.toLowerCase(); opt.textContent = n.charAt(0).toUpperCase()+n.slice(1); select.appendChild(opt); }); } else { ['asset','liability','equity','revenue','expense'].forEach(n => { const opt = document.createElement('option'); opt.value = n; opt.textContent = n.charAt(0).toUpperCase()+n.slice(1); select.appendChild(opt); }); } } catch(e){ const select = document.getElementById('accountTypeSelect'); select.innerHTML = '<option value="">Select Type</option>'; ['asset','liability','equity','revenue','expense'].forEach(n => { const opt = document.createElement('option'); opt.value = n; opt.textContent = n.charAt(0).toUpperCase()+n.slice(1); select.appendChild(opt); }); } }
loadAccountTypes();
document.getElementById('createAccountForm').addEventListener('submit', async function(e) { e.preventDefault(); const btn = this.querySelector('button[type=\"submit\"]'); btn.disabled = true; btn.textContent = 'Saving...'; const alert = document.getElementById('alertMessage'); alert.style.display = 'none'; try { const formData = new FormData(this); formData.append('action', 'create'); const response = await fetch('../api/accounts.php', { method: 'POST', body: formData }); const result = await response.json(); if (result.success) { alert.className = 'alert alert-success'; alert.textContent = 'Account created successfully! Redirecting...'; alert.style.display = 'block'; setTimeout(() => window.location.href = 'chart-of-accounts.php', 1500); } else { throw new Error(result.message || 'Failed to create account'); } } catch (error) { alert.className = 'alert alert-error'; alert.textContent = error.message; alert.style.display = 'block'; btn.disabled = false; btn.textContent = 'Save Account'; } });</script></body>
</html>

