<?php require_once '../../includes/functions.php'; requireLogin(); global $pdo; $search = $_GET['search'] ?? ''; $dept = $_GET['department'] ?? 'all'; $sql = "SELECT e.*, d.name as department_name FROM erp_employees e LEFT JOIN erp_departments d ON e.department_id = d.id WHERE 1=1"; $params = []; if ($search) { $sql .= " AND (e.first_name LIKE ? OR e.last_name LIKE ? OR e.email LIKE ?)"; $searchParam = "%$search%"; $params = [$searchParam, $searchParam, $searchParam]; } if ($dept !== 'all') { $sql .= " AND e.department_id = ?"; $params[] = $dept; } $sql .= " ORDER BY e.first_name ASC"; $stmt = $pdo->prepare($sql); $stmt->execute($params); $employees = $stmt->fetchAll(); $departments = $pdo->query("SELECT * FROM erp_departments ORDER BY name")->fetchAll(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees - ERP</title>
    <link rel="stylesheet" href="../../assets/css/style.css?v=<?= time() ?>">
    <style>* { margin: 0; padding: 0; box-sizing: border-box; } body { background: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; } .header { background: #fff; border-bottom: 1px solid #e0e0e0; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; } .header h1 { font-size: 1.5rem; font-weight: 500; } .container { max-width: 1400px; margin: 0 auto; padding: 24px; } .card { background: white; border-radius: 8px; border: 1px solid #e0e0e0; overflow: hidden; } .card-header { padding: 20px 24px; border-bottom: 1px solid #e0e0e0; } .filters { display: flex; gap: 12px; } .search-box { flex: 1; max-width: 400px; } .search-box input { width: 100%; padding: 10px 16px; border: 1px solid #dadce0; border-radius: 4px; font-size: 0.875rem; } .filter-select { padding: 10px 16px; border: 1px solid #dadce0; border-radius: 4px; font-size: 0.875rem; background: white; } .table { width: 100%; border-collapse: collapse; } .table th { text-align: left; padding: 12px 16px; font-size: 0.75rem; font-weight: 500; color: #5f6368; text-transform: uppercase; border-bottom: 1px solid #e0e0e0; background: #f8f9fa; } .table td { padding: 16px; border-bottom: 1px solid #f1f3f4; } .table tr:hover { background: #f8f9fa; } .btn { padding: 8px 16px; border-radius: 4px; text-decoration: none; font-size: 0.875rem; font-weight: 500; cursor: pointer; border: none; display: inline-block; } .btn-primary { background: #1a73e8; color: white; } .btn-secondary { background: #fff; color: #202124; border: 1px solid #dadce0; } .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 0.75rem; font-weight: 500; } .badge-success { background: #e6f4ea; color: #137333; } .badge-warning { background: #fef7e0; color: #b06000; } .badge-danger { background: #fce8e6; color: #c5221f; } .avatar { width: 32px; height: 32px; background: #1a73e8; color: white; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.875rem; font-weight: 500; margin-right: 12px; } .employee-cell { display: flex; align-items: center; }</style>
</head>
<body>
    <div class="header"><h1>ðŸ‘¥ Employees</h1><div class="header-actions"><a href="../index.php" class="btn btn-secondary">â† Back</a><a href="create-employee.php" class="btn btn-primary">+ New Employee</a></div></div>
    <div class="container"><div class="card"><div class="card-header"><form method="GET" class="filters"><div class="search-box"><input type="text" name="search" placeholder="Search employees..." value="<?= htmlspecialchars($search) ?>"></div><select name="department" class="filter-select" onchange="this.form.submit()"><option value="all">All Departments</option><?php foreach ($departments as $d): ?><option value="<?= $d['id'] ?>" <?= $dept == $d['id'] ? 'selected' : '' ?>><?= htmlspecialchars($d['name']) ?></option><?php endforeach; ?></select><button type="submit" class="btn btn-primary">Search</button></form></div>
    <table class="table"><thead><tr><th>Name</th><th>Department</th><th>Position</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php if (empty($employees)): ?><tr><td colspan="6" style="text-align: center; padding: 32px; color: #5f6368;">No employees found.</td></tr><?php else: ?><?php foreach ($employees as $emp): ?><tr><td><div class="employee-cell"><div class="avatar"><?= strtoupper(substr($emp['first_name'], 0, 1) . substr($emp['last_name'], 0, 1)) ?></div><div><div style="font-weight: 500;"><?= htmlspecialchars($emp['first_name'] . ' ' . $emp['last_name']) ?></div><div style="font-size: 0.75rem; color: #5f6368;">Joined <?= date('M Y', strtotime($emp['join_date'])) ?></div></div></div></td><td><?= htmlspecialchars($emp['department_name'] ?? '-') ?></td><td><?= htmlspecialchars($emp['position'] ?? '-') ?></td><td><?= htmlspecialchars($emp['email'] ?? '-') ?></td><td><?php $statusClass = ['active' => 'badge-success', 'terminated' => 'badge-danger', 'resigned' => 'badge-warning', 'on_leave' => 'badge-warning']; ?><span class="badge <?= $statusClass[$emp['status']] ?? 'badge-info' ?>"><?= ucfirst(str_replace('_', ' ', $emp['status'])) ?></span></td><td><a href="edit-employee.php?id=<?= $emp['id'] ?>" class="btn btn-secondary" style="padding: 4px 12px; font-size: 0.75rem;">Edit</a></td></tr><?php endforeach; ?><?php endif; ?>
    </tbody></table></div></div>
</body>
</html>

