<?php require_once '../../includes/functions.php'; requireLogin(); global $pdo; $month = $_GET['month'] ?? date('Y-m'); $sql = "SELECT p.*, e.first_name, e.last_name, e.position, d.name as department_name FROM erp_payroll p JOIN erp_employees e ON p.employee_id = e.id LEFT JOIN erp_departments d ON e.department_id = d.id WHERE DATE_FORMAT(p.payroll_month, '%Y-%m') = ? ORDER BY e.first_name ASC"; $stmt = $pdo->prepare($sql); $stmt->execute([$month]); $payroll = $stmt->fetchAll(); $totalBasic = 0; $totalAllowances = 0; $totalDeductions = 0; $totalNet = 0; foreach ($payroll as $p) { $totalBasic += $p['basic_salary']; $totalAllowances += $p['allowances']; $totalDeductions += $p['deductions']; $totalNet += $p['net_salary']; } ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payroll - ERP</title>
    <link rel="stylesheet" href="../../assets/css/style.css?v=<?= time() ?>">
    <style>* { margin: 0; padding: 0; box-sizing: border-box; } body { background: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; } .header { background: #fff; border-bottom: 1px solid #e0e0e0; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; } .header h1 { font-size: 1.5rem; font-weight: 500; } .container { max-width: 1400px; margin: 0 auto; padding: 24px; } .card { background: white; border-radius: 8px; border: 1px solid #e0e0e0; overflow: hidden; } .card-header { padding: 20px 24px; border-bottom: 1px solid #e0e0e0; display: flex; justify-content: space-between; align-items: center; } .filters { display: flex; gap: 12px; align-items: center; } .month-picker { padding: 8px 12px; border: 1px solid #dadce0; border-radius: 4px; font-size: 0.875rem; } .table { width: 100%; border-collapse: collapse; } .table th { text-align: left; padding: 12px 16px; font-size: 0.75rem; font-weight: 500; color: #5f6368; text-transform: uppercase; border-bottom: 1px solid #e0e0e0; background: #f8f9fa; } .table td { padding: 16px; border-bottom: 1px solid #f1f3f4; } .table tr:hover { background: #f8f9fa; } .btn { padding: 8px 16px; border-radius: 4px; text-decoration: none; font-size: 0.875rem; font-weight: 500; cursor: pointer; border: none; display: inline-block; } .btn-primary { background: #1a73e8; color: white; } .btn-secondary { background: #fff; color: #202124; border: 1px solid #dadce0; } .summary-cards { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 24px; } .summary-card { background: white; padding: 20px; border-radius: 8px; border: 1px solid #e0e0e0; } .summary-label { color: #5f6368; font-size: 0.875rem; margin-bottom: 8px; } .summary-value { font-size: 1.5rem; font-weight: 600; color: #202124; } .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 0.75rem; font-weight: 500; } .badge-warning { background: #fef7e0; color: #b06000; } .badge-success { background: #e6f4ea; color: #137333; }</style>
</head>
<body>
    <div class="header"><h1>ðŸ’° Payroll</h1><div class="header-actions"><a href="../index.php" class="btn btn-secondary">â† Back</a><a href="run-payroll.php" class="btn btn-primary">Run Payroll</a></div></div>
    <div class="container"><div class="summary-cards"><div class="summary-card"><div class="summary-label">Total Basic Salary</div><div class="summary-value">TSh <?= number_format($totalBasic, 2) ?></div></div><div class="summary-card"><div class="summary-label">Total Allowances</div><div class="summary-value" style="color: #137333;">+ TSh <?= number_format($totalAllowances, 2) ?></div></div><div class="summary-card"><div class="summary-label">Total Deductions</div><div class="summary-value" style="color: #c5221f;">- TSh <?= number_format($totalDeductions, 2) ?></div></div><div class="summary-card"><div class="summary-label">Net Payable</div><div class="summary-value" style="color: #1a73e8;">TSh <?= number_format($totalNet, 2) ?></div></div></div>
    <div class="card"><div class="card-header"><form method="GET" class="filters"><label style="font-weight: 500; margin-right: 8px;">Month:</label><input type="month" name="month" value="<?= $month ?>" class="month-picker" onchange="this.form.submit()"></form><?php if (!empty($payroll)): ?><button onclick="window.print()" class="btn btn-secondary">Print Report</button><?php endif; ?></div>
    <table class="table"><thead><tr><th>Employee</th><th>Department</th><th>Basic Salary</th><th>Allowances</th><th>Deductions</th><th>Net Salary</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php if (empty($payroll)): ?><tr><td colspan="8" style="text-align: center; padding: 48px; color: #5f6368;">No payroll records found for this month.<br><br><a href="run-payroll.php" class="btn btn-primary">Run Payroll for <?= date('F Y', strtotime($month)) ?></a></td></tr><?php else: ?><?php foreach ($payroll as $p): ?><tr><td><div style="font-weight: 500;"><?= htmlspecialchars($p['first_name'] . ' ' . $p['last_name']) ?></div><div style="font-size: 0.75rem; color: #5f6368;"><?= htmlspecialchars($p['position']) ?></div></td><td><?= htmlspecialchars($p['department_name'] ?? '-') ?></td><td><?= number_format($p['basic_salary'], 2) ?></td><td style="color: #137333;"><?= number_format($p['allowances'], 2) ?></td><td style="color: #c5221f;"><?= number_format($p['deductions'], 2) ?></td><td style="font-weight: 600;"><?= number_format($p['net_salary'], 2) ?></td><td><?php $statusClass = ['draft' => 'badge-warning', 'approved' => 'badge-success', 'paid' => 'badge-success']; ?><span class="badge <?= $statusClass[$p['status']] ?? 'badge-info' ?>"><?= ucfirst($p['status']) ?></span></td><td><a href="view-payslip.php?id=<?= $p['id'] ?>" class="btn btn-secondary" style="padding: 4px 12px; font-size: 0.75rem;">Payslip</a></td></tr><?php endforeach; ?><?php endif; ?>
    </tbody></table></div></div>
</body>
</html>

